#! /bin/sh

# kill everything
killall -q sxhkd

# programs
setxkbmap gb
setxkbmap -option caps:swapescape
sxhkd &

# workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# prefs
bspc config border_width            1
bspc config window_gap              10
bspc config split_ratio             0.55
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config focus_follows_pointer   true
