#! /bin/sh

# kill everything
killall -q sxhkd polybar nm-applet blueman-applet redshift-gtk

# programs
setxkbmap gb
setxkbmap -option caps:swapescape
sxhkd &

polybar example &
nm-applet &
blueman-applet &
redshift-gtk &
bgs ~/.wlp &

# workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# prefs
`sleep 3 && bspc config top_padding 20` &
bspc config border_width            1
bspc config window_gap              10
bspc config split_ratio             0.55
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config focus_follows_pointer   true

# rules
bspc rule -a Blueman-manager state=floating focus=on
bspc rule -a Org.gnome.Nautilus state=floating focus=on
