#! /bin/sh

# kill everything
killall -q sxhkd polybar nm-applet blueman-applet redshift xautolock picom

# programs
setxkbmap gb
setxkbmap -option caps:swapescape
sxhkd &

polybar example &
nm-applet &
blueman-applet &

[ -f ~/.fehbg ] && ~/.fehbg
redshift &
xautolock -locker "i3lock-fancy -f \"Fira Code Retina\" -t \"YILDIZ\" -g" &
picom --experimental-backends &

# workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# prefs
`sleep 1 && bspc config top_padding 20` &
bspc config border_width            2
bspc config normal_border_color     "#44475a"
bspc config active_border_color     "#6272a4"
bspc config focused_border_color    "#8be9fd"
bspc config presel_feedback_color   "#6272a4"
bspc config window_gap              10
bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config focus_follows_pointer   true

# rules
bspc rule -a Blueman-manager state=floating focus=on
